custombucket = "awsdevopsbucket"
table = "intellipaat"
databasehost = "intellipaat.c9seqsqu20in.us-east-1.rds.amazonaws.com"
duser = "admin"
dpass = "Laurax23"
s3database = "intellipaat"
kapp = "http://23.22.61.200:3000/"
